[project]
name = "app-backend"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "litestar[sqlalchemy,standard,structlog]>=2.16.0",
    "psycopg>=3.2.9",
    "pydantic-settings>=2.10.1",
]
